query MyNews {
  myNews {
    id
    title
    description
    date_of_pub
    cover {
      url
    }
    ContentZone {
      ... on ComponentBlogParagraphe {
        copy
      }
      ... on ComponentBlogMedias {
        images {
          url
        }
      }
      ... on ComponentBlogLinks {
        link
      }
    }
  }
}