query Articles {
    articles {
        id
        title
        copy
        image {
            url
        }
        date_of_pub
        category {
            name
        }
        ContentZone {
            ... on ComponentBlogParagraphe {
                copy
            }
            ... on ComponentBlogMedias {
                images {
                url
                }
            }
            ... on ComponentBlogLinks {
                link
            }
        }
    }
}