query projectsshowcases {
    projectsShowcases {
        id
        title
        description
        showcase {
            url
        }
        date_project
        version
        finished
        project_category
    }
}